name: renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "24 4 * * 1"

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      RENOVATE_REPOSITORIES: palmshed/linea

    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.LINEA_BOT_CLIENT_ID }}
          private-key: ${{ secrets.LINEA_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v7
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: renovatebot/github-action@v46.3.1
        with:
          configurationFile: renovate.json
          token: ${{ steps.app-token.outputs.token }}
